namespace ToyPadMaui.Services;

// Minimal in-app localization. Strings are keyed; T(key) returns the string
// for the current AppSettings.Language ("es" or "en"). Supports {0}/{1} args.
public static class Loc
{
    public static bool En => AppSettings.IsEnglish;

    public static string T(string key)
    {
        var map = En ? _en : _es;
        return map.TryGetValue(key, out var v) ? v : key;
    }

    public static string T(string key, params object[] args)
        => string.Format(T(key), args);

    static readonly Dictionary<string, string> _es = new()
    {
        // toolbar / status
        ["status.none"]   = "sin conexión",
        ["status.disc"]   = "desconectado",
        ["btn.about"]     = "¿Qué es?",
        ["btn.import"]    = "Importar",
        ["btn.connect"]   = "Conectar",
        ["btn.credits"]   = "Créditos",
        ["btn.lang"]      = "ES / EN",
        ["btn.mode.ps3"]  = "Modo: PS3",
        ["btn.mode.ps4"]  = "Modo: PS4",
        ["btn.install"]   = "Instalar",
        ["btn.install.ps3"] = "Instalar PS3",
        ["btn.install.ps4"] = "Instalar PS4",
        ["btn.sync"]      = "↻ Sincronizar",
        ["btn.clearall"]  = "Limpiar todo",
        ["btn.figs"]      = "🧩 Figuras",
        // zones
        ["zone.left"]   = "IZQUIERDA",
        ["zone.center"] = "CENTRO",
        ["zone.right"]  = "DERECHA",
        // categories
        ["cat.all"]   = "Todos",
        ["cat.char"]  = "Personajes",
        ["cat.veh"]   = "Vehículos",
        ["cat.gad"]   = "Gadgets",
        ["search.placeholder"] = "Buscar (Batman, TARDIS, ...)",
        ["hint.default"] = "Arrastra una figura a un espacio, o toca un espacio y luego una figura. Arrastra entre espacios para mover o intercambiar. Toca un espacio lleno para quitar.",
        // common buttons
        ["ok"] = "OK",
        ["cancel"] = "Cancelar",
        ["yes"] = "Sí",
        ["no"] = "No",
        ["install"] = "Instalar",
        ["later"] = "Más tarde",
        ["connect"] = "Conectar",
        ["close"] = "Cerrar",
        ["error"] = "Error",
        ["done"] = "Listo",
        // figure placement
        ["slot.firstTapEmpty"] = "Primero toca un espacio del Toy Pad",
        ["fig.notfound"] = "Figura no encontrada",
        ["swap.fail"] = "No puedo intercambiar (figura no encontrada)",
        ["moved"] = "Movido {0} → {1}",
        ["swapped"] = "Intercambio {0} ↔ {1}",
        ["placed"] = "{0} → {1}",
        ["removed"] = "Quitada de {0}",
        ["vehicle.saved"] = "{0} guardado (construido)",
        ["vehicle.tip.title"] = "Vehículos y gadgets",
        ["vehicle.tip.body"] = "Los vehículos y gadgets aparecen GENÉRICOS (en blanco) la primera vez, igual que con las figuras reales: el juego los construye dentro de la partida.\n\nCómo grabarlos:\n1. Coloca el vehículo/gadget y entra al juego.\n2. Constrúyelo en el juego (el portal de construcción) hasta dejarlo como quieras.\n3. Quítalo del pad en la app (o pulsa Sincronizar).\n\nLa app detecta que el juego lo construyó, descarga ese tag y lo guarda sobre tu archivo local. La próxima vez que lo coloques, ya aparece construido. Esto funciona en PS3 y PS4.",
        ["err.fmt"] = "Error: {0}",
        ["err.place.title"] = "Error al colocar figura",
        // import zip
        ["import.title"] = "Importar figuras (.zip)",
        ["import.body"] = "Para colocar figuras necesitas un archivo .zip con los volcados NFC (.bin) organizados en carpetas Characters, Vehicles y Gadgets.\n\nPor motivos legales estos archivos NO se incluyen en la app: son contenido del juego y cada quien debe aportar los suyos. Se guardan solo en este dispositivo, nunca se suben a ningún servidor.{0}\n\n¿Quieres seleccionar tu Dimensions.zip ahora?",
        ["import.ios"] = "\n\nNOTA iOS: si el selector de archivos no te deja elegir el zip (bug de iOS), descomprímelo y copia las carpetas Characters, Vehicles y Gadgets dentro de Archivos → En mi iPhone → LEGOPATCHER → Dimensions. También puedes abrir el zip desde Archivos y elegir Compartir → LEGOPATCHER.",
        ["import.pick"] = "Seleccionar zip",
        ["import.importing"] = "Importando...",
        ["import.done.title"] = "Importado",
        ["import.done.body"] = "Importadas {0} figuras.",
        ["import.err.title"] = "Error al importar",
        ["import.ios.title"] = "¿No puedes seleccionar el zip?",
        ["import.ios.body"] = "Es un bug de iOS con el selector de archivos. Alternativas:\n\n1) Abre el zip desde la app Archivos y elige Compartir → LEGOPATCHER.\n2) Descomprime el zip y copia las carpetas Characters, Vehicles y Gadgets a Archivos → En mi iPhone → LEGOPATCHER → Dimensions.",
        // console picker
        ["console.which"] = "¿Para qué consola?",
        ["console.ps3"] = "PS3 (webMAN / multiMAN)",
        ["console.ps4"] = "PS4 (GoldHEN)",
        ["connect.ps4.title"] = "Conectar a la PS4 (GoldHEN)",
        ["connect.ps4.body"] = "Para colocar figuras la app se conecta a tu PS4 por FTP (GoldHEN).\n\nNecesitas:\n• PS4 con GoldHEN y el Plugin Loader activo.\n• El servidor FTP de GoldHEN encendido (puerto 2121).\n• La IP local de la consola (Ajustes → Red → Ver estado de la conexión).\n\nLuego pulsa Instalar PS4 para subir el plugin y registrarlo en plugins.ini. Las figuras van a /data/toypad_emu/.\n\n¿Quieres configurar la conexión ahora?",
        ["connect.ps3.title"] = "Conectar a la PS3",
        ["connect.ps3.body"] = "Para colocar figuras la app se conecta a tu PS3 por FTP (webMAN MOD).\n\nNecesitas:\n• PS3 con jailbreak (HEN/CFW) y webMAN MOD con FTP activo.\n• La IP local de la consola (la ves en webMAN o en ajustes de red).\n\nLuego pulsa Instalar PS3 para subir el plugin y el EBOOT parcheado.\n\n¿Quieres configurar la conexión ahora?",
        // connect flow prompts
        ["connect.ps4.label"] = "Conectar a la PS4",
        ["connect.ps3.label"] = "Conectar a la PS3",
        ["connect.ip.ps4"] = "IP local de la PS4 (Ajustes > Red). FTP de GoldHEN en :2121:",
        ["connect.ip.ps3"] = "IP local de la PS3 (la ves en webMAN o ajustes de red):",
        ["connect.user"] = "Usuario FTP:",
        ["connect.pass"] = "Contraseña FTP (vacío suele bastar):",
        ["connect.testing"] = "Probando conexión...",
        ["connect.ok"] = "Conectado a {0} ({1})",
        ["connect.fail"] = "No se pudo conectar",
        ["connect.fail.ps3"] = "Sin conexión a la PS3",
        ["toast.mode.ps4"] = "Modo PS4 (FTP 2121)",
        ["toast.mode.ps3"] = "Modo PS3 (FTP 21)",
        ["platform.title"] = "Plataforma destino",
        // clear all
        ["clear.title"] = "Limpiar todo",
        ["clear.body"] = "¿Quitar las 7 figuras del Toy Pad?",
        ["clear.done"] = "Limpio",
        // install PS3
        ["install.ps3.title"] = "Instalar en la PS3",
        ["install.ps3.body"] = "Se subirá el plugin (toypad_emu.sprx) y se reemplazará el EBOOT.BIN del juego por el parcheado (se hace un respaldo del original). ¿Continuar?",
        ["install.ps3.uploadSprx"] = "Subiendo plugin...",
        ["install.ps3.uploadEboot"] = "Subiendo EBOOT.BIN (38 MB, tarda)...",
        ["install.ps3.done"] = "Instalación completada. Reinicia el juego desde el XMB para cargar el plugin.",
        // install PS4
        ["install.ps4.title"] = "Instalar en la PS4 (GoldHEN)",
        ["install.ps4.body"] = "Se subirá el plugin (toypad_emu.prx) a /data/GoldHEN/plugins/, se registrará en plugins.ini para CUSA00935, y se creará /data/toypad_emu/. Requiere GoldHEN con Plugin Loader y su FTP (2121) encendidos. ¿Continuar?",
        ["install.ps4.uploading"] = "Subiendo plugin .prx a GoldHEN...",
        ["install.ps4.done"] = "Plugin instalado y registrado. Reinicia el juego para que GoldHEN lo cargue. Las figuras van a /data/toypad_emu/.",
        // about / faq / credits
        ["about.title"] = "¿Qué es esto?",
        ["about.body"] = "Un emulador por software del Toy Pad de LEGO Dimensions para PS3 y PS4. Pones figuras, vehículos y gadgets en el juego sin el portal físico ni las figuras reales.\n\nCÓMO INSTALAR (PS3)\n1. Enciende la PS3 y activa el FTP en webMAN.\n2. Toca Conectar y escribe la IP local de tu PS3. Prueba la conexión.\n3. Toca Instalar PS3 y espera a que termine.\n4. Abre el juego y pon las figuras cuando quieras.\n\nCÓMO INSTALAR (PS4)\n1. Activa GoldHEN con el Plugin Loader y su FTP (puerto 2121).\n2. En la barra elige Modo: PS4, toca Conectar y escribe la IP de la PS4.\n3. Toca Instalar PS4: sube el plugin a /data/GoldHEN/plugins/ y lo registra en plugins.ini.\n4. Reinicia el juego y pon las figuras.\n\nREQUISITOS\nPS3 con jailbreak (HEN/CFW) + webMAN MOD, versión 1.22 americana (BLUS31473). O PS4 con GoldHEN, LEGO Dimensions CUSA00935 actualizado a 1.23.",
        ["about.faqbtn"] = "Ver preguntas frecuentes",
        ["faq.title"] = "Preguntas frecuentes",
        ["faq.body"] = "¿Necesito el portal o las figuras físicas?\nNo. Reemplaza el hardware por completo.\n\n¿De dónde salen los archivos de las figuras?\nTú los aportas (un .zip con los volcados .bin). Por motivos legales no se distribuyen; se guardan solo en este dispositivo.\n\n¿Sirve en cualquier PS3?\nSolo con jailbreak (HEN/CFW) y webMAN MOD. Por ahora únicamente la edición americana (BLUS31473), versión 1.22.\n\n¿Por qué los vehículos y gadgets salen en blanco?\nEs normal. El juego los muestra genéricos hasta su primera construcción dentro del juego, igual que con las figuras reales. Tras construirlos, al quitarlos o sincronizar la app guarda el vehículo ya construido, así la próxima vez aparece completo.\n\n¿Por qué importan los 7 espacios?\nEl Toy Pad tiene 1 espacio central, 3 a la izquierda y 3 a la derecha. El juego los usa de forma específica, así que izquierda y derecha no son intercambiables.\n\n¿Es seguro? ¿Toca mi juego?\nReemplaza el ejecutable del juego por uno modificado, pero hace un respaldo del original primero (EBOOT.BIN.original). Puedes revertirlo restaurándolo.",
        ["credits.title"] = "Créditos",
        ["credits.body"] = "Desarrollo: RadiantDelux — plugin, parche del EBOOT, protocolo e interfaz.\n\nProtocolo: basado en node-ld / ToyPadEmu.\n\nHerramientas: TrueAncestor SELF Resigner, scetool (naehrwert/flatz), SPRXPatcher (modificado), Cell SDK PPU, webMAN MOD / HEN.\n\nImágenes: LEGO Dimensions Wiki (Fandom). Los retratos son los mugshots oficiales de LEGO.com.\nLEGO y LEGO Dimensions son marcas de The LEGO Group. Proyecto no afiliado, sin fines de lucro.\n\nLos archivos .bin no se distribuyen; cada usuario importa los suyos y se guardan solo en este dispositivo.",
    };

    static readonly Dictionary<string, string> _en = new()
    {
        ["status.none"]   = "not connected",
        ["status.disc"]   = "disconnected",
        ["btn.about"]     = "What is this?",
        ["btn.import"]    = "Import",
        ["btn.connect"]   = "Connect",
        ["btn.credits"]   = "Credits",
        ["btn.lang"]      = "EN / ES",
        ["btn.mode.ps3"]  = "Mode: PS3",
        ["btn.mode.ps4"]  = "Mode: PS4",
        ["btn.install"]   = "Install",
        ["btn.install.ps3"] = "Install PS3",
        ["btn.install.ps4"] = "Install PS4",
        ["btn.sync"]      = "↻ Sync",
        ["btn.clearall"]  = "Clear all",
        ["btn.figs"]      = "🧩 Figures",
        ["zone.left"]   = "LEFT",
        ["zone.center"] = "CENTER",
        ["zone.right"]  = "RIGHT",
        ["cat.all"]   = "All",
        ["cat.char"]  = "Characters",
        ["cat.veh"]   = "Vehicles",
        ["cat.gad"]   = "Gadgets",
        ["search.placeholder"] = "Search (Batman, TARDIS, ...)",
        ["hint.default"] = "Drag a figure onto a space, or tap a space then a figure. Drag between spaces to move or swap. Tap a filled space to remove.",
        ["ok"] = "OK",
        ["cancel"] = "Cancel",
        ["yes"] = "Yes",
        ["no"] = "No",
        ["install"] = "Install",
        ["later"] = "Later",
        ["connect"] = "Connect",
        ["close"] = "Close",
        ["error"] = "Error",
        ["done"] = "Done",
        ["slot.firstTapEmpty"] = "First tap a Toy Pad space",
        ["fig.notfound"] = "Figure not found",
        ["swap.fail"] = "Can't swap (figure not found)",
        ["moved"] = "Moved {0} → {1}",
        ["swapped"] = "Swap {0} ↔ {1}",
        ["placed"] = "{0} → {1}",
        ["removed"] = "Removed from {0}",
        ["vehicle.saved"] = "{0} saved (built)",
        ["vehicle.tip.title"] = "Vehicles and gadgets",
        ["vehicle.tip.body"] = "Vehicles and gadgets show up GENERIC (blank) the first time, just like with real figures: the game builds them inside the save.\n\nHow to save them:\n1. Place the vehicle/gadget and enter the game.\n2. Build it in the game (the build portal) however you like.\n3. Remove it from the pad in the app (or tap Sync).\n\nThe app detects the game built it, downloads that tag and saves it over your local file. Next time you place it, it shows up already built. This works on PS3 and PS4.",
        ["err.fmt"] = "Error: {0}",
        ["err.place.title"] = "Error placing figure",
        ["import.title"] = "Import figures (.zip)",
        ["import.body"] = "To place figures you need a .zip with the NFC dumps (.bin) organized into Characters, Vehicles and Gadgets folders.\n\nFor legal reasons these files are NOT bundled with the app: they are game content and each user must provide their own. They are stored only on this device and never uploaded to any server.{0}\n\nDo you want to select your Dimensions.zip now?",
        ["import.ios"] = "\n\niOS NOTE: if the file picker won't let you choose the zip (iOS bug), unzip it and copy the Characters, Vehicles and Gadgets folders into Files → On My iPhone → LEGOPATCHER → Dimensions. You can also open the zip from Files and choose Share → LEGOPATCHER.",
        ["import.pick"] = "Select zip",
        ["import.importing"] = "Importing...",
        ["import.done.title"] = "Imported",
        ["import.done.body"] = "Imported {0} figures.",
        ["import.err.title"] = "Import error",
        ["import.ios.title"] = "Can't select the zip?",
        ["import.ios.body"] = "It's an iOS bug with the file picker. Alternatives:\n\n1) Open the zip from the Files app and choose Share → LEGOPATCHER.\n2) Unzip it and copy the Characters, Vehicles and Gadgets folders to Files → On My iPhone → LEGOPATCHER → Dimensions.",
        ["console.which"] = "Which console?",
        ["console.ps3"] = "PS3 (webMAN / multiMAN)",
        ["console.ps4"] = "PS4 (GoldHEN)",
        ["connect.ps4.title"] = "Connect to PS4 (GoldHEN)",
        ["connect.ps4.body"] = "To place figures the app connects to your PS4 over FTP (GoldHEN).\n\nYou need:\n• PS4 with GoldHEN and the Plugin Loader enabled.\n• GoldHEN's FTP server on (port 2121).\n• The console's local IP (Settings → Network → View Connection Status).\n\nThen tap Install PS4 to upload the plugin and register it in plugins.ini. Figures go to /data/toypad_emu/.\n\nDo you want to set up the connection now?",
        ["connect.ps3.title"] = "Connect to PS3",
        ["connect.ps3.body"] = "To place figures the app connects to your PS3 over FTP (webMAN MOD).\n\nYou need:\n• PS3 with jailbreak (HEN/CFW) and webMAN MOD with FTP enabled.\n• The console's local IP (shown in webMAN or in network settings).\n\nThen tap Install PS3 to upload the plugin and the patched EBOOT.\n\nDo you want to set up the connection now?",
        ["connect.ps4.label"] = "Connect to PS4",
        ["connect.ps3.label"] = "Connect to PS3",
        ["connect.ip.ps4"] = "PS4 local IP (Settings > Network). GoldHEN FTP on :2121:",
        ["connect.ip.ps3"] = "PS3 local IP (shown in webMAN or network settings):",
        ["connect.user"] = "FTP user:",
        ["connect.pass"] = "FTP password (empty usually works):",
        ["connect.testing"] = "Testing connection...",
        ["connect.ok"] = "Connected to {0} ({1})",
        ["connect.fail"] = "Could not connect",
        ["connect.fail.ps3"] = "No connection to the PS3",
        ["toast.mode.ps4"] = "PS4 mode (FTP 2121)",
        ["toast.mode.ps3"] = "PS3 mode (FTP 21)",
        ["platform.title"] = "Target platform",
        ["clear.title"] = "Clear all",
        ["clear.body"] = "Remove the 7 figures from the Toy Pad?",
        ["clear.done"] = "Cleared",
        ["install.ps3.title"] = "Install on PS3",
        ["install.ps3.body"] = "The plugin (toypad_emu.sprx) will be uploaded and the game's EBOOT.BIN replaced with the patched one (the original is backed up). Continue?",
        ["install.ps3.uploadSprx"] = "Uploading plugin...",
        ["install.ps3.uploadEboot"] = "Uploading EBOOT.BIN (38 MB, takes a while)...",
        ["install.ps3.done"] = "Install complete. Restart the game from the XMB to load the plugin.",
        ["install.ps4.title"] = "Install on PS4 (GoldHEN)",
        ["install.ps4.body"] = "The plugin (toypad_emu.prx) will be uploaded to /data/GoldHEN/plugins/, registered in plugins.ini for CUSA00935, and /data/toypad_emu/ will be created. Requires GoldHEN with Plugin Loader and its FTP (2121) enabled. Continue?",
        ["install.ps4.uploading"] = "Uploading .prx plugin to GoldHEN...",
        ["install.ps4.done"] = "Plugin installed and registered. Restart the game so GoldHEN loads it. Figures go to /data/toypad_emu/.",
        ["about.title"] = "What is this?",
        ["about.body"] = "A software emulator of the LEGO Dimensions Toy Pad for PS3 and PS4. Place characters, vehicles and gadgets in the game without the physical portal or real figures.\n\nHOW TO INSTALL (PS3)\n1. Turn on the PS3 and enable FTP in webMAN.\n2. Tap Connect and enter your PS3's local IP. Test the connection.\n3. Tap Install PS3 and wait for it to finish.\n4. Open the game and place figures anytime.\n\nHOW TO INSTALL (PS4)\n1. Enable GoldHEN with the Plugin Loader and its FTP (port 2121).\n2. In the toolbar pick Mode: PS4, tap Connect and enter the PS4's IP.\n3. Tap Install PS4: it uploads the plugin to /data/GoldHEN/plugins/ and registers it in plugins.ini.\n4. Restart the game and place figures.\n\nREQUIREMENTS\nPS3 with jailbreak (HEN/CFW) + webMAN MOD, version 1.22 US (BLUS31473). Or PS4 with GoldHEN, LEGO Dimensions CUSA00935 updated to 1.23.",
        ["about.faqbtn"] = "See FAQ",
        ["faq.title"] = "FAQ",
        ["faq.body"] = "Do I need the portal or physical figures?\nNo. It fully replaces the hardware.\n\nWhere do the figure files come from?\nYou provide them (a .zip with the .bin dumps). For legal reasons they are not distributed; they are stored only on this device.\n\nDoes it work on any PS3?\nOnly with jailbreak (HEN/CFW) and webMAN MOD. For now only the US edition (BLUS31473), version 1.22.\n\nWhy do vehicles and gadgets show up blank?\nThat's normal. The game shows them generic until their first build inside the game, just like with real figures. After building one, removing it or syncing makes the app save the built vehicle, so next time it shows up complete.\n\nWhy do the 7 spaces matter?\nThe Toy Pad has 1 center space, 3 on the left and 3 on the right. The game uses them specifically, so left and right are not interchangeable.\n\nIs it safe? Does it touch my game?\nIt replaces the game executable with a modified one, but backs up the original first (EBOOT.BIN.original). You can revert by restoring it.",
        ["credits.title"] = "Credits",
        ["credits.body"] = "Development: RadiantDelux — plugin, EBOOT patch, protocol and interface.\n\nProtocol: based on node-ld / ToyPadEmu.\n\nTools: TrueAncestor SELF Resigner, scetool (naehrwert/flatz), SPRXPatcher (modified), Cell SDK PPU, webMAN MOD / HEN.\n\nImages: LEGO Dimensions Wiki (Fandom). Portraits are the official LEGO.com mugshots.\nLEGO and LEGO Dimensions are trademarks of The LEGO Group. Unaffiliated, non-profit project.\n\nThe .bin files are not distributed; each user imports their own and they are stored only on this device.",
    };
}
